version: "3"

services:
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''

  postgres:
    image: postgres:10.15
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
